/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as WorkoutTemplateIdRouteImport } from './routes/workout.$templateId'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppStopwatchRouteImport } from './routes/_app/stopwatch'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as AppExercisesRouteImport } from './routes/_app/exercises'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const WorkoutTemplateIdRoute = WorkoutTemplateIdRouteImport.update({
  id: '/workout/$templateId',
  path: '/workout/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppStopwatchRoute = AppStopwatchRouteImport.update({
  id: '/stopwatch',
  path: '/stopwatch',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AppCalendarRoute
  '/exercises': typeof AppExercisesRoute
  '/stats': typeof AppStatsRoute
  '/stopwatch': typeof AppStopwatchRoute
  '/templates': typeof AppTemplatesRoute
  '/workout/$templateId': typeof WorkoutTemplateIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/calendar': typeof AppCalendarRoute
  '/exercises': typeof AppExercisesRoute
  '/stats': typeof AppStatsRoute
  '/stopwatch': typeof AppStopwatchRoute
  '/templates': typeof AppTemplatesRoute
  '/workout/$templateId': typeof WorkoutTemplateIdRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/exercises': typeof AppExercisesRoute
  '/_app/stats': typeof AppStatsRoute
  '/_app/stopwatch': typeof AppStopwatchRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/workout/$templateId': typeof WorkoutTemplateIdRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendar'
    | '/exercises'
    | '/stats'
    | '/stopwatch'
    | '/templates'
    | '/workout/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/calendar'
    | '/exercises'
    | '/stats'
    | '/stopwatch'
    | '/templates'
    | '/workout/$templateId'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/calendar'
    | '/_app/exercises'
    | '/_app/stats'
    | '/_app/stopwatch'
    | '/_app/templates'
    | '/workout/$templateId'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  WorkoutTemplateIdRoute: typeof WorkoutTemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/workout/$templateId': {
      id: '/workout/$templateId'
      path: '/workout/$templateId'
      fullPath: '/workout/$templateId'
      preLoaderRoute: typeof WorkoutTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stopwatch': {
      id: '/_app/stopwatch'
      path: '/stopwatch'
      fullPath: '/stopwatch'
      preLoaderRoute: typeof AppStopwatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises': {
      id: '/_app/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppExercisesRoute: typeof AppExercisesRoute
  AppStatsRoute: typeof AppStatsRoute
  AppStopwatchRoute: typeof AppStopwatchRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppExercisesRoute: AppExercisesRoute,
  AppStatsRoute: AppStatsRoute,
  AppStopwatchRoute: AppStopwatchRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  WorkoutTemplateIdRoute: WorkoutTemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
